/**
 * @typedef FieldType
 * 
 * @property {string} help_text Text that will appear in the editor via tooltip to assist the content creator. Best used for information that is supplementary but not required to use the field.
 * @property {string} id Unique id for a field. This is generated by HubSpot. When building locally you do not need to specify this id.
 * @property {string} inline_help_text Help text that will be shown inline below the label of the field (limit 300 chars). Best used for information required to use the field.
 * @property {string} label The text the content creator sees describing the field. May contain spaces.
 * @property {boolean} locked Determines if the field is editable in the content editor. If true, the field will not appear in the content editor.
 * @property {string} name The variable name you will use to refer to this field's values, and is what the value of the field is stored against. Cannot contain spaces or special characters. If no name is provided, it will default to a lower  snake case value of the label.
 * @property {boolean} required Determines if the field can be left blank in the editor. If true, content will not be allowed to publish without filling out this field.
 * @property {string} type The type of field see field types below for documentation on all field types. {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields#field-types}
 * @property {Array} visibility Determines the display conditions for a field.
 * @property {'half_width'|null} display_width Allows for side by side module fields in content editors, rather than full-width fields, when set to "half_width". The field will appear side-by-side with the next field in the fields.json file, as long as that field is also set to "half_width".
 */

/**
 * Base Field Class
 * Should only be used as parent to extend new classes.
 * 
 * @see {@link https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields-overview}
 * @see {@link https://developers.hubspot.com/en/docs/cms/building-blocks/module-theme-fields}
 * 
 * @since 2.0.0
 */
 module.exports = class _HublField {

	/**
	 * Base Field Constructor
	 * @param {FieldType} data
	 */
	constructor(data) {
		this.data = Object.assign({
			type: "",
			name: "field",
			label: "Field",
			required: false,
			locked: false,
			inline_help_text: "",
			help_text: "",
			visibility: {},
			display_width: null
		}, data);
	}

	/**
	 * Return the fields as JSON. Used in Transform process.
	 * @private
	 */
	toJSON() {
		return this.data;
	}

    /**
     * Will Prevent this field from being transformed
     * @param {Boolean} flag
     */
	dontTransform(flag = true) {
        this.data.dontTransform = !!flag;
        return this;
	}

    /**
     * Set any key.
     * @param {string} key 
     * @param {string} value 
     */
	set(key, value) {
		key = key.toLowerCase()
		if (key == 'type') {
			return this
		}
        this.data[key] = value;
        return this;
	}

    /**
     * Set name and label
     * @param {String} name 
     * @param {String} label 
     */
    name(name, label) {
        this.data.name = name;
        this.data.label = label;
        return this;
    }

    /**
     * Set label
     * @param {String} label 
     */
    label(label) {
        this.data.label = label;
        return this;
    }
	
	/**
     * Set id
     * @param {String} id 
     */
	id(id) {
        this.data.id = id;
        return this;
	}
	 
    /**
     * Determines if the field can be left blank in the editor. If true, content will not be allowed to publish without filling out this field.
     * @param {boolean}
     */
    required(required = true) {
        this.data.required = !!required;
        return this;
    }

    /**
     * Determines if the field is editable in the content editor. If "true", the field will not appear in the content editor.
     * @param {boolean} 
     */
    locked(locked = true) {
        this.data.locked = !!locked;
        return this;
    }

    /**
     * Set inline help text
     * @param {String} text 
     */
    inlineHelpText(text) {
        this.data.inline_help_text = text;
        return this;
    }

    /**
     * Set help text
     * @param {String} text 
     */
    helpText(text) {
        this.data.help_text = text;
        return this;
    }

    /**
     * Set default value of field
     * @param {*} value 
     */
    default(value) {
        this.data.default = value;
        return this;
	}

    /**
     * Set field Visibility
     * @param {string} controllingField The controlling field name. Including nesting with group.name
     * @param string} regex The comparing value
     * @param {string} type Comparison type. Eg. 'EQUAL' etc.
     */
    visibleIf(controllingField, regex, type = "EQUAL") {
        if (!this.data.visibility) {
            this.data.visibility = {};
        }

        this.data.visibility = Object.assign(this.data.visibility, {
            controlling_field: controllingField,
            controlling_value_regex: regex,
            operator: type,
        });

        return this;
    }

    /**
     * Enable repeater
     * @param {Object} overrides 
     */
    repeat(overrides = {}) {
        this.data.occurrence = Object.assign({
            min: null,
            max: null,
            sorting_label_field: null,
            default: null
        }, overrides);
        this.data.default = [];

        return this;
    }

    /**
     * 
     * @param {object} subFields eg. {opacity: true}
     */
    hiddenSubfields(subFields) {
        if (!this.data.visibility) {
            this.data.visibility = {};
        }

        this.data.visibility.hidden_subfields = subFields;
        return this;
    }

	/**
     * Set Apply to field if condition is true
     * @param {Boolean} condition 
     * @param {Function} callback 
     */
	applyIf(condition, callback) {
		if (!!condition) {
			return callback(this)
        }
        return this;
    }
	
}